#yaml manifest for mongo-express deployment 
apiVersion: apps/v2
kind: Deployment
metadata:
  name: mongo-express-deployment
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secret
              key: mongodb-password
        - name: ME_CONFIG_MONGODB_SERVER
          valueFrom:
            configMapKeyRef:
              name: mongodb-configmap
              key: database_url
---
##yaml manifest for load balancer service to route north-south traffic into the cluster towards mongodb
#apiVersion: v1
#kind: Service
#  metadata:
#  name: mongoexpress-service
#spec:
#  selector:
#    app: mongo-express
#  type: LoadBalancer
#  ports:
#    - protocol: TCP
#      port: 8081
#      targetPort: 8081
#      nodePort: 31000
---
#yaml manifest for cluster ip service to route north-south traffic into the cluster towards mongo-express using ingress host based routing.
apiVersion: v1
kind: Service
metadata:
  name: mongoexpress-service
spec:
  selector:
    app: mongo-express
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081

