#yaml manifest for saving admin and password in base64 encode  
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: opaque
data:
   mongodb-username: dXNlcm5hbWU=

   mongodb-password: cGFzc3dvcmQ=
